-- Disable RLS for import
ALTER TABLE contractor DISABLE ROW LEVEL SECURITY;
ALTER TABLE keyword DISABLE ROW LEVEL SECURITY;
ALTER TABLE contractor_keyword DISABLE ROW LEVEL SECURITY;
ALTER TABLE contractor_history DISABLE ROW LEVEL SECURITY;

-- After import, you can re-enable with:
-- ALTER TABLE contractor ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE keyword ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE contractor_keyword ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE contractor_history ENABLE ROW LEVEL SECURITY;