-- Re-enable RLS after import
ALTER TABLE contractor ENABLE ROW LEVEL SECURITY;
ALTER TABLE keyword ENABLE ROW LEVEL SECURITY;
ALTER TABLE contractor_keyword ENABLE ROW LEVEL SECURITY;
ALTER TABLE contractor_history ENABLE ROW LEVEL SECURITY;